server:
  port: 8761

spring:
  application:
    name: discovery-service

eureka:
  client:
    register-with-eureka: false # discovery server ? ?????
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0 # ?????? ?????? ???? ??  ??? ??

